version: "3.1"
services:
  app_apivendas:
    container_name: app_apivendas   
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./api/:/var/www/api
      - ./api/public/:/var/www/api/public    
    networks:
      - imoveis_network
    restart: always  
    networks:
      - apivendas_network  
networks:
  apivendas_network: